name: Reusable build workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: poetry

      - name: Install dependencies
        run: poetry install

      - name: Build distributions
        run: poetry build

