name: Publish to PyPI

on:
  release:
    types:
      - 'released'

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    steps:
      - name: Build distributions
        uses: './.github/workflows/build.yaml'

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
