name: Publish to TestPyPI

on:
  push:
    branches:
      - main

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    steps:
      - name: Build distributions
        uses: './.github/workflows/build.yaml'

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
